lib/macroy_web/router.ex
defmodule MacroyWeb.Router do
  use MacroyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug Doorman.Login.Session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MacroyWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/user", UserController, only: [:new, :create]
    get "/login", SessionController, :signin
    post "/login", SessionController, :create
    get "/logout", SessionController, :logout

    scope "/orgfiles" do
      pipe_through MacroyWeb.RequireLogin
      resources "/", OrgFileController, only: [
        :index,
        :show,
        :new,
        :create,
        :edit,
        :update
      ]
      get "/upload/:id", OrgFileController, :upload
    end

    scope "/todos" do
      pipe_through MacroyWeb.RequireLogin
      get "/", TodoController, :index
      live "/new", Live.TodoNew, session: [:user_id]
      get "/:id", TodoController, :show
    end
  end
  # Other scopes may use custom stacks.
  # scope "/api", MacroyWeb do
  #   pipe_through :api
  # end
end

lib/macroy_web/views/layout_view.ex
defmodule MacroyWeb.LayoutView do
  use MacroyWeb, :view
end

lib/macroy_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <%= csrf_meta_tag() %>
        <title>Macroy</title>
        <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
        <script src="https://kit.fontawesome.com/15bf290da4.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <header>
      <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <a href="<%= Routes.page_path(@conn, :index) %>" class="navbar-item">
            <img src="<%= Routes.static_path(@conn, "/images/macroy_banner.png") %>" alt="Macroy Logo" width="224" height="56" />
          </a>
          <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
        <div id="macroy-navbar" class="navbar-menu">
          <div class="navbar-start">
            <a href="<%= Routes.page_path(@conn, :index) %>" class="navbar-item">
              Home
            </a>
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                OrgFiles
              </a>
              <div class="navbar-dropdown">
                  <a href="<%= Routes.org_file_path(@conn, :new)%>" class="navbar-item">
                      New
                  </a>
                  <a href="<%= Routes.org_file_path(@conn, :index)%>" class="navbar-item">
                      Index
                  </a>
              </div>
            </div>
            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                    Todos
                </a>
                <div class="navbar-dropdown">
                    <a href="<%= Routes.live_path(@conn, MacroyWeb.Live.TodoNew)%>" class="navbar-item">
                        New
                    </a>
                    <a href="<%= Routes.todo_path(@conn, :index)%>" class="navbar-item">
                        Index
                    </a>
                </div>
            </div>
          </div>
          <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons">
                <%= unless Doorman.logged_in? @conn do %>
                    <a href="<%= Routes.user_path(@conn, :new) %> " class="button is-primary">
                        <strong>Sign up</strong>
                    </a>
                    <a href="<%= Routes.session_path(@conn, :signin) %>" class="button is-light">
                        Log in
                    </a>
                <% end %>
                <%= if Doorman.logged_in? @conn do %>
                    <a href="<%= Routes.session_path(@conn, :logout) %>" class="button is-light">
                        Log out
                    </a>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
        <%= Enum.map(get_flash(@conn), fn {flash_key, flash_message} -> %>
            <div class="notification is-<%= flash_key %>">
                <button class="delete"></button>
                <%= flash_message %>
            </div>
        <% end) %>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>">
    </script>
    <script type="text/javascript">
     document.addEventListener('DOMContentLoaded', () => {
         (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
             $notification = $delete.parentNode;
             $delete.addEventListener('click', () => {
                 $notification.parentNode.removeChild($notification);
             });
         });
     });
    </script>
  </body>
</html>